name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Instalar dependências
        run: npm install

      - name: Executar testes unitários com Jest
        run: npm test

      - name: Analisar código com CodeQL
        uses: github/codeql-action/analyze@v2

      - name: Verificar qualidade do código
        run: echo "Verificando qualidade do código..."
