name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Faz o checkout do código no repositório

    - name: Install dependencies
      run: npm install  # Instala as dependências do npm

    - name: Run tests
      run: |
        echo "Executando testes..."
        # Aqui você colocaria seus comandos de teste reais

    - name: Code quality check
      run: |
        echo "Verificando qualidade do código..."

